### ISSUE TITLE
Entering a Nether portal mounted now causes a ticking entity crash.

### ISSUE THREAD

**Issue by Barerock** [CodeF53/Horse-Buff#76] opened 2024-09-05 18:59 UTC
Neruina catches this ticking entity in the nether occasionally and now whenever I enter the nether riding a horse, which is the _only_ way to get a horse into the nether, a ticking player event occurs. I am on the other side when relogging and the horse is back in the overworld.

I was previously able to traverse, but this now happens.
[latest.log](https://github.com/user-attachments/files/16899073/latest.log)

**Comment by Barerock** [comment] 2024-09-05 19:05
Okay, pushing the horse through worked after traveling and unloading the horse. Going through after the horse is through works fine.

**Comment by CodeF53** [comment] 2024-10-03 00:38
Duplicate of #75 [I don't support older versions of horsebuff and portal code is now gone from new versions]

**Closed by CodeF53** 2024-10-03 00:38 UTC
